DROP SCHEMA IF EXISTS nekodb;
CREATE DATABASE nekodb;
USE nekodb;

CREATE TABLE USERS (
    email VARCHAR(128) PRIMARY KEY,
    password VARCHAR(60) NOT NULL,
    username VARCHAR(255) NOT NULL
);

CREATE TABLE CATS (
    cat_id VARCHAR(32) PRIMARY KEY,
    url VARCHAR(255) NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL
);

CREATE TABLE FAVOURITES (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    cat_id VARCHAR(32) NOT NULL,
    user_email VARCHAR(128) NOT NULL,
    FOREIGN KEY (cat_id) REFERENCES CATS(id),
    FOREIGN KEY (user_email) REFERENCES USERS(email)
);

CREATE TABLE POSTS (
    post_id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(128) NOT NULL,
    title VARCHAR(128) NOT NULL,
    comments VARCHAR(254) NOT NULL,
    ratings FLOAT NOT NULL,
    likes INT NOT NULL,
    date VARCHAR(16) NOT NULL,
    imageUUID VARCHAR(8) NOT NULL,
    FOREIGN KEY (email) REFERENCES USERS(email)
);

CREATE TABLE IMAGES (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    post_id INT NOT NULL,
    imageUUID VARCHAR(8) NOT NULL,
    image BLOB NOT NULL,
    FOREIGN KEY (post_id) REFERENCES POSTS(post_id)
);
